### ISSUE TITLE
Can't send anything?

### ISSUE THREAD

**Issue by Atherz97** [chasinglogic/Chattie#15]
Noobie here, I got the tool working, however when it's supposed to send a message, an exception is thrown:

```
Message received...
Someone is talking to me...
Parsed:  ['cribbin_bot']
Exception thrown during sync
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/matrix_client/client.py", line 335, in listen_forever
    self._sync(timeout_ms)
  File "/usr/lib/python3.6/site-packages/matrix_client/client.py", line 451, in _sync
    room._put_event(event)
  File "/usr/lib/python3.6/site-packages/matrix_client/room.py", line 251, in _put_event
    listener['callback'](self, event)
  File "/usr/lib/python3.6/site-packages/chattie/connectors/matrix.py", line 69, in parse_event
    incoming_event['content']['body'])
  File "/usr/lib/python3.6/site-packages/chattie/bot.py", line 119, in parse_message
    self.send_message(room_id, reply)
AttributeError: 'Bot' object has no attribute 'send_message'
```

My code (only 1 handler):
```
def main_handler(bot, msg, **kwargs):
    print(msg)
    return "yo"
    
handlers = [
    main_handler
]
```
pip is updated, matrix_client is installed, and I see in the source code there is no send_message method. Am I missing something obvious?

**Comment by chasinglogic** [comment]
Did you install chattie via pip or using the master branch?

**Comment by Atherz97** [comment]
Via pip. Is that not the most up to date version?

**Comment by chasinglogic** [comment]
Nope that should work, I'll take a look at this tomorrow. Thanks for the bug report!

**Comment by chasinglogic** [comment]
So it looks like I forgot to publish v0.2.0 a while ago and therefore pushed a broken version. I fixed a few bugs with v0.2.0 and verified that your bot as given works!

```
python/test_bot λ chattie run
Booting systems...
Hello my name is chattie...
Inventory gathered...
Commands and handlers loaded...
Listening for messages...
Make sure to include your bot name in the message. Type quit to exit.
>> test
Message received...
test
yo
>>
```

Let me know if you have any more issues after upgrading to 0.2.1 you can do this by running:

```
pip3 install -U chattie
```

**Comment by Atherz97** [comment]
Thank you!
